### ISSUE TITLE
about the dataset

### ISSUE THREAD

**Issue by cs123951** [iRB-Lab/PPG#2]
What's the data from? 
I cloned your code, and ran `python segment.py`, but I don't understand what's the data for the code.
For example, what's the data in `data/raw` from? How can I get data? Using sensor to get?
In my knowledge, the data needed for PPG is pictures of skin.
Or an you link some paper about PPG?

Thanks a lot!

**Comment by iROCKBUNNY** [comment]
Sorry, this is just an experimental project. The data are available.

**Comment by cs123951** [comment]
I noticed there are three PPG repositories under iRB-Lab, what's the difference between them?
"The data are available" means I can get the data on the Internet? Then how to get?

**Comment by iROCKBUNNY** [comment]
Sorry, it was a typo. I mean the data are NOT available.

**Comment by iROCKBUNNY** [comment]
Those three PPG repositories are our experimental projects with different set-ups.

**Comment by cs123951** [comment]
Could you give some reference papers? Thanks!

**Comment by iROCKBUNNY** [comment]
Unfortunately, I CANNOT provide you any references at this time. However, there might be any reference publications in the future.
